---
- name: ADD YUM REPO
  hosts: STAGING_SERVERS 
  become: yes

  tasks:
  - name: Add repo
    yum_repository:
     name: app
     description: custom app repo
     baseurl: http://www.cumulogic.com/download/Apps/guestbookapp.zip
